### ISSUE TITLE
Issue using converter when all images are not anpimg/ig

### ISSUE THREAD

**Issue by Tuhnesie** [thomaslilja/anpimg-converter#1]
When using converter and all images are not the same tag, a problem occurs. I can't find any connection on how it appears, but as shown in the image below it removes different parts of different tags/lines depending on how many occurrences there are.

![image](https://cloud.githubusercontent.com/assets/15437822/20661398/e3bedea6-b54e-11e6-8201-cba84c4fa8e0.png)

**Comment by thomaslilja** [comment]
Can't reproduce.
